config/routes.rb
Rails.application.routes.draw do
  # 前台
  resources :posts, only: [:show]

  # 后台
  namespace :admin, path: :console do
    root to: 'dashboard#home'
    resources :posts, except: [:show]
    resources :comments, only: [:index, :destroy]
    resources :tags, except: [:show]
    resources :users
    resources :admins, only: [:show, :edit, :update]
    controller :admins do
      get :profile, action: :show
      get 'profile/edit', action: :edit
      put :profile, action: :update
      patch :profile, action: :update
    end

    resource :sessions, only: [:new, :create, :destroy]
    controller :sessions do
      get :login, action: :new
      post :login, action: :create
      delete :logout, action: :destroy
    end
    resource :change_passwords, only: [:new, :create],
                                path_names: { new: '' },
                                path: :change_password
    resource :searchs, only: [:show], path: :search

    controller :dashboard do
      get :home, action: :home
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  layout 'admin_no_box'

  before_action :authorize_dashboard

  def home
    @posts_count = Post.count
    @tags_count = Tag.count
    @comments_count = Comment.count
    @users_count = User.count
  end

  private

    def authorize_dashboard
      authorize(:dashboard, "#{action_name}?".to_sym)
    end

end

app/views/admin/dashboard/home.html.erb
<div class="row">
  <div class="col-lg-3 col-xs-6">
    <div class="small-box bg-aqua">
      <div class="inner">
        <h3><%= @posts_count %><span style="font-size: 20px">篇</span></h3>
        <p>文章</p>
      </div>
      <div class="icon"><i class="fa fa-files-o"></i></div>
      <%= link_to admin_posts_path, class: 'small-box-footer' do %>
        查看详情 <i class="fa fa-arrow-circle-right"></i>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3 col-xs-6">
    <div class="small-box bg-green">
      <div class="inner">
        <h3><%= @tags_count %><span style="font-size: 20px">个</span></h3>
        <p>标签</p>
      </div>
      <div class="icon"><i class="fa fa-tags"></i></div>
      <%= link_to admin_tags_path, class: 'small-box-footer' do %>
        查看详情 <i class="fa fa-arrow-circle-right"></i>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3 col-xs-6">
    <div class="small-box bg-yellow">
      <div class="inner">
        <h3><%= @comments_count %><span style="font-size: 20px">条</span></h3>
        <p>评论</p>
      </div>
      <div class="icon"><i class="fa fa-comments-o"></i></div>
      <%= link_to admin_comments_path, class: 'small-box-footer' do %>
        查看详情 <i class="fa fa-arrow-circle-right"></i>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3 col-xs-6">
    <div class="small-box bg-red">
      <div class="inner">
        <h3><%= @users_count %><span style="font-size: 20px">个</span></h3>
        <p>用户</p>
      </div>
      <div class="icon"><i class="fa fa-users"></i></div>
      <%= link_to admin_users_path, class: 'small-box-footer' do %>
        查看详情 <i class="fa fa-arrow-circle-right"></i>
      <% end %>
    </div>
  </div>
</div>

<% content_for :breadcrumb do %>
  <li>
    <%= link_to 'javascript:;' do %>
      <i class="fa fa-dashboard"></i>
      仪表盘
    <% end %>
  </li>
<% end %>
<% content_for :page_title, '仪表盘' %>