config/routes.rb
Rails.application.routes.draw do
  # 前台
  resources :posts, only: [:show]

  # 后台
  namespace :admin, path: :console do
    root to: 'dashboard#home'
    resources :posts, except: [:show]
    resources :comments, only: [:index, :destroy]
    resources :tags, except: [:show]
    resources :users
    resources :admins, only: [:show, :edit, :update]
    controller :admins do
      get :profile, action: :show
      get 'profile/edit', action: :edit
      put :profile, action: :update
      patch :profile, action: :update
    end

    resource :sessions, only: [:new, :create, :destroy]
    controller :sessions do
      get :login, action: :new
      post :login, action: :create
      delete :logout, action: :destroy
    end
    resource :change_passwords, only: [:new, :create],
                                path_names: { new: '' },
                                path: :change_password
    resource :searchs, only: [:show], path: :search

    controller :dashboard do
      get :home, action: :home
    end
  end
end

app/views/layouts/admin/_flash_message.html.erb
<% if flash.present? %>
  <% flash.each do |msg_type, msg| %>
    <div class="alert alert-<%= msg_type %> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/admin/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b>1.0
  </div>
  <strong>Copyright &copy; 2015 winterwhisper.</strong> All rights reserved.
</footer>

app/views/layouts/admin/_header.html.erb
<header class="main-header">
  <%= link_to admin_root_path, class: 'logo' do %>
    <span class="logo-mini">后台</span>
    <span class="logo-lg">后台管理系统</span>
  <% end %>

  <nav class="navbar navbar-static-top" role="navigation">
    <a href="javascript:;" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only"></span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_admin.avatar_url(:thumb), class: 'user-image', alt: "User Image" %>
            <span class="hidden-xs"><%= current_admin.name %></span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <%= image_tag current_admin.avatar_url(:thumb), class: 'img-circle', alt: "User Image" %>
              <p>
                <%= current_admin.nickname %>
                <small><%= current_admin.email %></small>
              </p>
            </li>
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to '用户资料', admin_profile_path, class: 'btn btn-default btn-flat' %>
                <%= link_to '修改密码', new_admin_change_passwords_path, class: "btn btn-default btn-flat" %>
              </div>
              <div class="pull-right">
                <%= link_to '退出', admin_logout_path, method: :delete, class: 'btn btn-default btn-flat' %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag current_admin.avatar_url(:thumb), class: 'img-circle', alt: "User Image" %>
      </div>
      <div class="pull-left info">
        <p><%= current_admin.name %></p>
      </div>
    </div>

    <%= form_for(:search, url: admin_searchs_path, method: :get, html: { class: 'sidebar-form' }) do |f| %>
      <div class="input-group">
        <%= f.text_field :q, class: 'form-control', placeholder: '搜索...' %>
        <span class="input-group-btn">
          <%= f.button class: 'btn btn-flat' do %>
            <i class="fa fa-search"></i>
          <% end %>
        </span>
      </div>
    <% end %>

    <ul class="sidebar-menu">
      <li class="header">导航</li>
      <li class="<%= render_sidenav_highlight('dashboard', 'home') %>">
        <%= link_to admin_root_path do %>
          <i class='fa fa-dashboard'></i>
          <span>仪表盘</span>
        <% end %>
      </li>
      <li class="treeview <%= render_sidenav_highlight('posts', nil, params[:tag].blank?) %>">
        <%= link_to 'javascript:;' do %>
          <i class='fa fa-files-o'></i>
          <span>文章</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>
        <ul class="treeview-menu">
          <li class="<%= render_sidenav_highlight('posts', 'index', params[:tag].blank?) %>">
            <%= link_to admin_posts_path do %>
              <i class='fa fa-circle-o'></i>
              <span>所有文章</span>
            <% end %>
          </li>
          <li class="<%= render_sidenav_highlight('posts', 'new', params[:tag].blank?) %>">
            <%= link_to new_admin_post_path do %>
              <i class='fa fa-circle-o'></i>
              <span>新建文章</span>
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview <%= render_sidenav_highlight('tags') %>">
        <%= link_to 'javascript:;' do %>
          <i class='fa fa-tags'></i>
          <span>标签</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>
        <ul class="treeview-menu">
          <li class="<%= render_sidenav_highlight('tags', 'index') %>">
            <%= link_to admin_tags_path do %>
              <i class='fa fa-circle-o'></i>
              <span>所有标签</span>
            <% end %>
          </li>
          <li class="<%= render_sidenav_highlight('tags', 'new') %>">
            <%= link_to new_admin_tag_path do %>
              <i class='fa fa-circle-o'></i>
              <span>新建标签</span>
            <% end %>
          </li>
        </ul>
      </li>
      <li class="<%= render_sidenav_highlight('comments') %>">
        <%= link_to admin_comments_path do %>
          <i class='fa fa-comments-o'></i> <span>评论</span>
        <% end %>
      </li>
      <li class="<%= render_sidenav_highlight('users') %>">
        <%= link_to 'javascript:;' do %>
          <i class='fa fa-users'></i> <span>用户</span>
        <% end %>
      </li>
      <li class="header">标签</li>
      <% if @tags.present? %>
        <% @tags.each do |tag| %>
          <li class="<%= controller_name == 'posts' and params[:tag].present? and params[:tag] == tag.value ? 'active' : '' %>">
            <%= link_to admin_posts_path(tag: tag.value) do %>
              <i class='fa fa-circle-o'></i> <span><%= tag.value %></span>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </section>
</aside>