config/routes.rb
Rails.application.routes.draw do
  # 前台
  resources :posts, only: [:show]

  # 后台
  namespace :admin, path: :console do
    root to: 'dashboard#home'
    resources :posts, except: [:show]
    resources :comments, only: [:index, :destroy]
    resources :tags, except: [:show]
    resources :users
    resources :admins, only: [:show, :edit, :update]
    controller :admins do
      get :profile, action: :show
      get 'profile/edit', action: :edit
      put :profile, action: :update
      patch :profile, action: :update
    end

    resource :sessions, only: [:new, :create, :destroy]
    controller :sessions do
      get :login, action: :new
      post :login, action: :create
      delete :logout, action: :destroy
    end
    resource :change_passwords, only: [:new, :create],
                                path_names: { new: '' },
                                path: :change_password
    resource :searchs, only: [:show], path: :search

    controller :dashboard do
      get :home, action: :home
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  SPLIT_STR = ','

  has_many :post_tags
  has_many :posts, through: :post_tags

  validates_presence_of :value

  before_save :strip_value

  def self.split_tags_value(tag)
    tag.split(Tag::SPLIT_STR)
  end

  private

    def strip_value
      self.value.strip!
    end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController

  before_action :set_tag, except: :index
  before_action :authorize_tag, except: :index

  def index
    @tags = policy_scope(Tag).page(params[:page])
  end

  def create
    if @tag.save
      flash[:success] = '标签创建成功'
      redirect_to admin_tags_url
    else
      flash.now[:danger] = '标签创建失败'
      render :new
    end
  end

  def update
    if @tag.update_attributes(tag_params)
      flash[:success] = '标签修改成功'
      redirect_to admin_tags_url
    else
      flash.now[:danger] = '标签修改失败'
      render :edit
    end
  end

  def destroy
    @tag.destroy
    flash[:success] = '标签删除成功'
    redirect_to admin_tags_url
  end

  private

    def set_tag
      if params[:id]
        @tag = Tag.find(params[:id])
      else
        @tag = params[:tag] ? Tag.new(tag_params) : Tag.new
      end
    end

    def tag_params
      params.require(:tag).permit(:value)
    end

    def authorize_tag
      authorize @tag
    end

end

app/views/admin/tags/_form.html.erb
<%= form_for([:admin, @tag], html: { class: 'form-horizontal' }) do |f| %>
  <div class="form-group <%= render_form_error_class(@tag, :value) %>">
    <%= f.label :value, '内容', class: 'col-xs-12 col-sm-1 control-label' %>
    <div class="col-xs-12 col-sm-11 col-md-10">
      <%= f.text_field :value, class: 'form-control', placeholder: '请输入标签内容' %>
      <%= render_form_error_message(@tag, :value) %>
    </div>
  </div>
  <%= f.submit '提交', class: 'btn btn-success col-sm-offset-1 col-md-offset-1 col-xs-12 col-sm-1' %>
<% end %>

app/views/admin/tags/edit.html.erb
<%= render 'form' %>

<% content_for :breadcrumb do %>
  <li>
    <%= link_to admin_tags_path do %>
      <i class="fa fa-tags"></i>
      所有标签
    <% end %>
  </li>
  <li><%= link_to '编辑标签', edit_admin_tag_path(@tag) %></li>
<% end %>
<% content_for :page_title, '编辑标签' %>
<% content_for :box_title, '编辑标签' %>
<% content_for :box_actions do %>
  <%= link_to '返回', admin_tags_path, class: 'btn btn-default btn-sm' %>
<% end %>

app/views/admin/tags/index.html.erb
<% if @tags.present? %>
  <table class="table">
    <thead>
    <th>标签内容</th>
    <th>文章数</th>
    <th>创建时间</th>
    <th>操作</th>
    </thead>
    <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.value %></td>
        <td><%= tag.posts.size %></td>
        <td><%= time_formater(tag.created_at) %></td>
        <td>
          <%= link_to '编辑', edit_admin_tag_path(tag), class: 'btn btn-xs btn-default' %>
          <%= link_to '删除', admin_tag_path(tag), method: :delete, class: 'btn btn-xs btn-danger', 'data-confirm' => '确定要删除吗？' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  目前还没有标签
<% end %>

<% content_for :breadcrumb do %>
  <li>
    <%= link_to 'javascript:;' do %>
      <i class="fa fa-tags"></i>
      所有标签
    <% end %>
  </li>
<% end %>
<% content_for :page_title, '所有标签' %>
<% content_for :box_title, '标签列表' %>
<% content_for :box_actions do %>
  <%= link_to '添加标签', new_admin_tag_path, class: 'btn btn-default btn-sm' %>
<% end %>
<% content_for :box_footer do %>
  <%= paginate @tags %>
<% end %>

app/views/admin/tags/new.html.erb
<%= render 'form' %>

<% content_for :breadcrumb do %>
  <li>
    <%= link_to admin_tags_path do %>
      <i class="fa fa-tags"></i>
      所有标签
    <% end %>
  </li>
  <li><%= link_to '新建标签', new_admin_tag_path %></li>
<% end %>
<% content_for :page_title, '新建标签' %>
<% content_for :box_title, '新建标签' %>
<% content_for :box_actions do %>
  <%= link_to '返回', admin_tags_path, class: 'btn btn-default btn-sm' %>
<% end %>