config/routes.rb
Rails.application.routes.draw do
  # 前台
  resources :posts, only: [:show]

  # 后台
  namespace :admin, path: :console do
    root to: 'dashboard#home'
    resources :posts, except: [:show]
    resources :comments, only: [:index, :destroy]
    resources :tags, except: [:show]
    resources :users
    resources :admins, only: [:show, :edit, :update]
    controller :admins do
      get :profile, action: :show
      get 'profile/edit', action: :edit
      put :profile, action: :update
      patch :profile, action: :update
    end

    resource :sessions, only: [:new, :create, :destroy]
    controller :sessions do
      get :login, action: :new
      post :login, action: :create
      delete :logout, action: :destroy
    end
    resource :change_passwords, only: [:new, :create],
                                path_names: { new: '' },
                                path: :change_password
    resource :searchs, only: [:show], path: :search

    controller :dashboard do
      get :home, action: :home
    end
  end
end

app/views/admin/admins/_form.html.erb
<%= form_for([:admin, current_admin], html: { class: 'form-horizontal', multipart: true }) do |f| %>
  <div class="form-group">
    <%= f.label :id, 'Id', class: 'col-xs-12 col-sm-1 control-label' %>
    <div class="col-xs-12 col-sm-11 col-md-10">
      <%= f.text_field :id, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, '用户名', class: 'col-xs-12 col-sm-1 control-label' %>
    <div class="col-xs-12 col-sm-11 col-md-10">
      <%= f.text_field :name, class: 'form-control', disabled: 'disabled' %>
    </div>
  </div>
  <div class="form-group <%= render_form_error_class(current_admin, :nickname) %>">
    <%= f.label :nickname, '昵称', class: 'col-xs-12 col-sm-1 control-label' %>
    <div class="col-xs-12 col-sm-11 col-md-10">
      <%= f.text_field :nickname, class: 'form-control', placeholder: '请输入昵称' %>
      <%= render_form_error_message(current_admin, :nickname) %>
    </div>
  </div>
  <div class="form-group <%= render_form_error_class(current_admin, :email) %>">
    <%= f.label :email, 'Email', class: 'col-xs-12 col-sm-1 control-label' %>
    <div class="col-xs-12 col-sm-11 col-md-10">
      <%= f.text_field :email, class: 'form-control', placeholder: '请输入Email' %>
      <%= render_form_error_message(current_admin, :email) %>
    </div>
  </div>
  <div class="form-group <%= render_form_error_class(current_admin, :avatar) %>">
    <%= f.label :avatar, '头像', class: 'col-xs-12 col-sm-1 control-label', style: current_admin.avatar? ? 'line-height: 179px' : '' %>
    <div class="col-xs-12 col-sm-11 col-md-10">
      <%= image_tag current_admin.avatar_url(:thumb), class: 'avatar form-avatar mb10' if current_admin.avatar? %>
      <%= f.file_field :avatar, class: 'form-control', placeholder: '请输入标题' %>
      <%= f.hidden_field :avatar_cache %>
      <%= render_form_error_message(current_admin, :avatar) %>
      <% if current_admin.avatar? %>
        <label class="mt10">
          <%= f.check_box :remove_avatar %>
          删除头像
        </label>
      <% end %>
    </div>
  </div>
  <%= f.submit '提交', class: 'btn btn-success col-sm-offset-1 col-md-offset-1 col-xs-12 col-sm-1' %>
<% end %>

app/views/admin/admins/edit.html.erb
<%= render 'form' %>

<% content_for :breadcrumb do %>
  <li>
    <%= link_to admin_profile_path do %>
      <i class="fa fa-user"></i>
      用户资料
    <% end %>
  </li>
  <li><%= link_to '修改用户资料', admin_profile_edit_path %></li>
<% end %>
<% content_for :page_title, '修改用户资料' %>
<% content_for :box_title, '用户资料' %>
<% content_for :box_actions do %>
  <%= link_to '返回', admin_profile_path, class: 'btn btn-default btn-sm' %>
<% end %>

app/views/admin/admins/show.html.erb
<div class="row mt20">
  <div class="col-sm-offset-1 col-sm-1">
    Id
  </div>
  <div class="col-sm-9">
    <%= current_admin.id %>
  </div>
</div>
<div class="row mt20">
  <div class="col-sm-offset-1 col-sm-1">
    用户名
  </div>
  <div class="col-sm-9">
    <%= current_admin.name %>
  </div>
</div>
<div class="row mt20">
  <div class="col-sm-offset-1 col-sm-1">
    昵称
  </div>
  <div class="col-sm-9">
    <%= current_admin.nickname %>
  </div>
</div>
<div class="row mt20 mb20">
  <div class="col-sm-offset-1 col-sm-1">
    电子邮箱
  </div>
  <div class="col-sm-9">
    <%= current_admin.email %>
  </div>
</div>
<div class="row mt20">
  <div class="col-sm-offset-1 col-sm-1 mb20" style="<%= current_admin.avatar? ? 'line-height: 160px' : '' %>">
    头像
  </div>
  <div class="col-sm-9">
    <%= image_tag current_admin.avatar_url(:thumb), class: 'avatar' %>
  </div>
</div>

<% content_for :breadcrumb do %>
  <li>
    <%= link_to 'javascript:;' do %>
      <i class="fa fa-user"></i>
      用户资料
    <% end %>
  </li>
<% end %>
<% content_for :page_title, '用户资料' %>
<% content_for :box_title, '用户资料' %>
<% content_for :box_actions do %>
  <%= link_to '修改', admin_profile_edit_path, class: 'btn btn-default btn-sm' %>
<% end %>